# Generated by Django 5.2.5 on 2025-11-16 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('device_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('device_type', models.CharField(choices=[('light', 'Đèn'), ('fan', 'Quạt'), ('ac', 'Điều hòa'), ('socket', 'Ổ cắm'), ('door', 'Cửa'), ('sensor', 'Cảm biến'), ('dryer', 'Máy sấy')], max_length=20)),
                ('room', models.CharField(choices=[('living_room', 'Phòng khách'), ('bedroom', 'Phòng ngủ'), ('kitchen', 'Nhà bếp'), ('bathroom', 'Phòng tắm'), ('outside', 'Bên ngoài'), ('corridor', 'Hành lang')], max_length=20)),
                ('is_on', models.BooleanField(default=False)),
                ('status', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('old_status', models.JSONField(default=dict)),
                ('new_status', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('on', 'Bật thiết bị'), ('off', 'Tắt thiết bị')], max_length=10)),
                ('scheduled_time', models.TimeField()),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('repeat_type', models.CharField(choices=[('once', 'Một lần'), ('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần')], default='once', max_length=10)),
                ('repeat_days', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_executed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceUsageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_sessions', to='devices.device')),
            ],
            options={
                'db_table': 'device_usage_sessions',
            },
        ),
        migrations.CreateModel(
            name='DeviceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('turn_on_count', models.IntegerField(default=0)),
                ('total_usage_minutes', models.IntegerField(default=0)),
                ('power_consumption', models.FloatField(default=0.0)),
                ('cost', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='devices.device')),
            ],
            options={
                'db_table': 'device_statistics',
                'unique_together': {('device', 'date')},
            },
        ),
    ]
