# Generated by Django 5.2.5 on 2025-10-04 02:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('light', 'Đèn'), ('fan', 'Quạt'), ('ac', 'Điều hòa'), ('socket', 'Ổ cắm'), ('door', 'Cửa')], max_length=20)),
                ('room', models.CharField(choices=[('living_room', 'Phòng khách'), ('bedroom', 'Phòng ngủ'), ('kitchen', 'Nhà bếp'), ('bathroom', 'Phòng tắm'), ('outside', 'Bên ngoài')], max_length=20)),
                ('is_on', models.BooleanField(default=False)),
                ('status', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('old_status', models.JSONField(default=dict)),
                ('new_status', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.device')),
            ],
            options={
                'db_table': 'device_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
