# Generated by Django 5.2.5 on 2025-10-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUsageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_sessions', to='devices.device')),
            ],
            options={
                'db_table': 'device_usage_sessions',
            },
        ),
        migrations.CreateModel(
            name='DeviceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('turn_on_count', models.IntegerField(default=0)),
                ('total_usage_minutes', models.IntegerField(default=0)),
                ('power_consumption', models.FloatField(default=0.0)),
                ('cost', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='devices.device')),
            ],
            options={
                'db_table': 'device_statistics',
                'unique_together': {('device', 'date')},
            },
        ),
    ]
