# Generated by Django 5.2.5 on 2025-11-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_deviceusagesession_devicestatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('light', 'Đèn'), ('fan', 'Quạt'), ('ac', 'Điều hòa'), ('socket', 'Ổ cắm'), ('door', 'Cửa'), ('sensor', 'Cảm biến'), ('dryer', 'Máy sấy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.CharField(choices=[('living_room', 'Phòng khách'), ('bedroom', 'Phòng ngủ'), ('kitchen', 'Nhà bếp'), ('bathroom', 'Phòng tắm'), ('outside', 'Bên ngoài'), ('corridor', 'Hành lang')], max_length=20),
        ),
    ]
